import {redirect} from "next/dist/server/api-utils";
import Head from "next/head";
import React from "../../public/SVG/technologies/react.svg";
import MainMenu from "../../components/mainMenu/mainMenu";
import { theme } from "../../styles/theme";
import { titles } from "../../constants";
import HeaderService from "../../components/ServicePage/HeaderService";

const menuLabelsColor = theme.colors.black;

const Industry = ({ title, text }) => {
  return (
      <>
        <Head>
          <title>{title}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <>
          <MainMenu
            backgroundColor={'none'}
            titlesColor={menuLabelsColor}
            titles={titles}
          >
            <HeaderService title={title} text={text}/>
          </MainMenu>
        </>
      </>
  )
}

export default Industry;

const industries = [
  'Logistics',
  'Delivery & Shipping',
  'EduTech',
  'Healthcare',
  'ECommerce',
  'Legal Services',
  'Booking systems',
  'Cryptocurrency'
]

Industry.getInitialProps = async ({ query }) => {
  const text = 'Make a significant leap forward to innovative logistics solutions for enhancing the performance of the shipping industry with your tech ideas.'

  return {
    title: query.industry,
    text
  }
}
