import { useEffect, useState } from "react";
import { useQuery } from "@apollo/client";
import Head from "next/head";
import FooterComponent from "../../components/Footer";
import HeaderInsights from "../../components/InsightsPage/HeaderInsights";
import MainMenu from "../../components/mainMenu/mainMenu";
import React from "../../public/SVG/technologies/react.svg";
import { footer, titles } from "../../constants";
import { useIsMobile } from "../../services/hooks";
import { theme } from "../../styles/theme";
import { GET_INSIGHTS_PAGE } from "../../graphql/insights/queries";
import Custom404 from "../404";
import { GetInsightsPage } from "../../graphql/insights/__generated__/GetInsightsPage";

const Insights = () => {
  const { data, loading, error } = useQuery<GetInsightsPage>(GET_INSIGHTS_PAGE);
  const industries = data?.industries?.data;
  const insightsEntry = data?.insightsPage?.data?.attributes;
  const title = insightsEntry?.title;
  const text = insightsEntry?.description;
  const inputPlaceholder = insightsEntry?.searchBarText;

  const {isMobile, isTablet, isSmallTablet} = useIsMobile();

  const [menuColor, setMenuColor] = useState("none");
  const handleScroll = () => {
    window.scrollY >= 25
      ? setMenuColor(theme.colors.white)
      : setMenuColor("none");
  };

  useEffect(() => {
    window.addEventListener("scroll", handleScroll);

    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  const renderCondition = industries && title && text && inputPlaceholder;

  if (loading) return null;
  if (error) return <Custom404 />;

  return (
    <>
      {renderCondition && (
        <>
          <Head>
            <title>Incora | Insights</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <>
            <MainMenu
              backgroundColor={isMobile || isTablet || isSmallTablet
                ? theme.colors.white
                : menuColor}
              titlesColor={theme.colors.black}
              titles={titles}
            >
              <HeaderInsights
                industries={industries}
                title={title}
                text={text}
                inputPlaceholder={inputPlaceholder}
              />
            </MainMenu>
            <FooterComponent />
          </>
        </>
      )}
    </>
  );
};

export default Insights;