import HeaderInsights from "../../components/InsightsPage/HeaderInsights";
import Head from "next/head";
import React from "../../public/SVG/technologies/react.svg";
import MainMenu from "../../components/mainMenu/mainMenu";
import { theme } from "../../styles/theme";
import { footer, titles } from "../../constants";
import { useEffect, useState } from "react";
import FooterComponent from "../../components/Footer";

const header = {
  title: 'Discover what’s inside the IT space',
  text: 'Tech & Business Articles to get you integrated into the Software Development environment.'
}

const news = {
  title: "Insights",
  articles: [
    {
      img: "./newsBlock/newImg1.jpg",
      tags: ["tagtitle", "tagtitle"],
      categories: ["category"],
      title: "How Voice Technology can upgrade your app? [Installation Guide Included]",
      redirectTo: "[With the Use of Apache Kafka]",
    },
    {
      img: "./newsBlock/newImg2.jpg",
      tags: ["tagtitle"],
      categories: ["category", "category"],
      title: "What is The Role of CI/CD Pipeline in Software Development?",
      redirectTo: "Incora Is Gaining Popularity On Clutch",
    },
    {
      img: "./newsBlock/newImg1.jpg",
      tags: ["tagtitle"],
      categories: ["category", "category"],
      title: "Why AWS is a great choice for deployment? [Installation Insights]",
      redirectTo:
          "How to Monetize Delivery and Shipping Apps: Methods Screening",
    },
    {
      img: "./newsBlock/newImg1.jpg",
      tags: ["tagtitle", "tagtitle"],
      categories: ["category"],
      title: "What to expect from Web Summit: Our Experience in 2021",
      redirectTo: "[With the Use of Apache Kafka]",
    },
    {
      img: "./newsBlock/newImg2.jpg",
      tags: ["tagtitle"],
      categories: ["category", "category"],
      title: "Incora is Named a Top Development Ukrainian Firm by Clutch!",
      redirectTo: "Incora Is Gaining Popularity On Clutch",
    },
    {
      img: "./newsBlock/newImg3.jpg",
      tags: ["tagtitle", "tagtitle"],
      categories: ["category"],
      title: "How to Monetize Delivery and Shipping Apps: Methods Screening",
      redirectTo: "Node.js vs Python: What are the Pros, Cons, and Use Cases?",
    },
    {
      img: "./newsBlock/newImg3.jpg",
      tags: ["tagtitle", "tagtitle"],
      categories: ["category"],
      title: "Intro to Microservices Communication [With the Use of Apache Kafka]",
      redirectTo: "Node.js vs Python: What are the Pros, Cons, and Use Cases?",
    },
    {
      img: "./newsBlock/newImg1.jpg",
      tags: ["tagtitle"],
      categories: ["category", "category"],
      title: "Incora Is Gaining Popularity On Clutch",
      redirectTo:
          "How to Monetize Delivery and Shipping Apps: Methods Screening",
    },
    {
      img: "./newsBlock/newImg1.jpg",
      tags: ["tagtitle"],
      categories: ["category", "category"],
      title: "Node.js vs Python: What are the Pros, Cons, and Use Cases?",
      redirectTo:
          "How to Monetize Delivery and Shipping Apps: Methods Screening",
    },
  ],
};

const inputPlaceholder = 'Search by name, title, or title name';

const Insights = () => {
  const [menuColor, setMenuColor] = useState('none');
  const handleScroll = () => {
    window.scrollY >= 25
        ? setMenuColor(theme.colors.white)
        : setMenuColor('none')
  }

  useEffect(() => {
    window.addEventListener('scroll', handleScroll)

    return () => window.removeEventListener('scroll', handleScroll);
  })

  return (
    <>
      <Head>
        <title>Incora | Insights</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <MainMenu
            backgroundColor={menuColor}
            titlesColor={theme.colors.black}
            titles={titles}
        >
          <HeaderInsights
            title={header.title}
            text={header.text}
            inputPlaceholder={inputPlaceholder}
            news={news.articles}
          />
        </MainMenu>
        <FooterComponent
          policies={footer.policies}
          offices={footer.offices}
          pages={footer.pages}
          followUs={footer.followUs}
          copyright={footer.copyright}
        />
      </>
    </>
  )
}

export default Insights;
