import Head from "next/head";
import React from "../../../public/SVG/technologies/react.svg";
import MainMenu from "../../../components/mainMenu/mainMenu";
import { theme } from "../../../styles/theme";
import { titles } from "../../../constants";
import HeaderService from "../../../components/ServicePage/HeaderService";
import OfferedSolutions from "../../../components/ExpertisePage/OfferedSolutions";
import { useEffect, useState } from "react";
import NewsComponent from "../../../components/News";
import ContactUsComponent from "../../../components/Homepage/ContactUs";
import { IContactUs } from "@interfaces";
import FooterComponent from "../../../components/Footer";
import { IFooter } from "../../../interfaces/footer.interface";
import Facebook from "../../../public/SVG/socialNetwork/facebook.svg";
import LinkedIn from "../../../public/SVG/socialNetwork/linkedIn.svg";
import Instagram from "../../../public/SVG/socialNetwork/instagram.svg";
import { useRouter } from "next/router";
import { useQuery } from "@apollo/client";
import { GET_INDUSTRY_PAGE } from "../../../graphql/industries/queries";
import Custom404 from "../../404";
import { GetIndustryPage } from "../../../graphql/industries/__generated__/GetIndustryPage";
import EmbodiedIdeasComponent from "../../../components/Homepage/EmbodiedIdeas";

const colorWhite = theme.colors.white;
const colorBlack = theme.colors.black;
const hexagonColorGrey = theme.elements.hexagonBorderedGrey;

const contactUs: IContactUs = {
  title: "contact us",
  text: "Let’s create progress together!",
  formLabels: ["name", "phone number", "email", "what is you main goal?"],
  addresses: [
    { "ukrainian office": "2 Horodotska Str.,\n" + "Lviv 75001 Ukraine" },
    { "Usa office": "16192 Coastal Hwy, Lewes,\n" + "DE 19958 USA" },
  ],
  buttonLabel: "send",
};

const footer: IFooter = {
  policies: ["privacy policy", "Cookies Policy"],
  offices: contactUs.addresses,
  pages: ["Services", "expertise", "Case Studies", "Company", "Insights"],
  followUs: [
    { icon: Facebook, redirectTo: "Facebook" },
    { icon: LinkedIn, redirectTo: "LinkedIn" },
    { icon: Instagram, redirectTo: "Instagram" },
  ],
  copyright: "© 2015-2022 Incora LLC",
};

const Industry = () => {
  const router = useRouter();
  const { industry } = router.query;

  const { data, loading, error } = useQuery<GetIndustryPage>(
    GET_INDUSTRY_PAGE,
    {
      variables: {
        url: industry,
      },
    }
  );
  const entry = data?.industries?.data[0].attributes;
  const headerTitle = entry?.name;
  const headerDescription = entry?.description;
  const headerIcon = entry?.icon?.data?.attributes;
  const offeredSolutionsIntro = entry?.offeredSolutions?.intro;
  const offeredSolutionsData = entry?.offeredSolutions?.items;
  const contactUsTitle = entry?.contactUs?.title;
  const contactUsSubtitle = entry?.contactUs?.subtitle;
  const newsTitle = entry?.insights.intro;
  const articles = entry?.insights.articles?.data;
  const projects = entry?.projects?.data;

  const [menuColor, setMenuColor] = useState("none");
  const handleScroll = () => {
    window.scrollY >= 50 ? setMenuColor(colorWhite) : setMenuColor("none");
  };

  useEffect(() => {
    window.addEventListener("scroll", handleScroll);

    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  const renderCondition =
    headerTitle &&
    headerDescription &&
    headerIcon &&
    offeredSolutionsIntro &&
    offeredSolutionsData &&
    contactUsTitle &&
    contactUsSubtitle &&
    newsTitle &&
    articles &&
    projects;

  if (loading) return null;
  if (error) return <Custom404 />;

  return (
    <>
      {renderCondition && (
        <>
          <Head>
            <title>Incora | Industries</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <>
            <MainMenu
              backgroundColor={menuColor}
              titlesColor={colorBlack}
              titles={titles}
            >
              <HeaderService
                title={headerTitle}
                titleSize={"64px"}
                icon={headerIcon}
                text={headerDescription}
                textWidth={"560px"}
                hexagonColor={hexagonColorGrey}
                bgColor={colorWhite}
              />
              <OfferedSolutions
                intro={offeredSolutionsIntro}
                data={offeredSolutionsData}
              />
              <EmbodiedIdeasComponent
                bgColor={theme.colors.yellow}
                elementsColor={theme.colors.black}
                projects={projects}
                disablePadding
                disableSeeMore
              />
              <NewsComponent title={newsTitle} articles={articles} />
              <ContactUsComponent
                title={contactUsTitle}
                text={contactUsSubtitle}
                formLabels={contactUs.formLabels}
                addresses={contactUs.addresses}
                buttonLabel={contactUs.buttonLabel}
              />
            </MainMenu>
            <FooterComponent
              policies={footer.policies}
              offices={footer.offices}
              followUs={footer.followUs}
              pages={footer.pages}
              copyright={footer.copyright}
            />
          </>
        </>
      )}
    </>
  );
};

export default Industry;
