import {footer, IServicesDataInfoBestSuitedFor, IServicesDataInfoContent, servicesData, titles} from "../../constants";
import MainMenu from "../../components/mainMenu/mainMenu";
import {theme} from "../../styles/theme";
import HeaderService from "../../components/ServicePage/HeaderService";
import { IService, IServiceCTX } from "@interfaces";
import Head from "next/head";
import React from "../../public/SVG/technologies/react.svg";
import FooterComponent from "../../components/Footer";
import LetsTalk from "../../components/Services/LetsTalk";
import Information from "../../components/ServicePage/Information";
import BestSuitedFor from "../../components/ServicePage/BestSuitedFor";
import WorkflowSetUp from "../../components/ServicePage/WorkflowSetUp";
import FAQ from "../../components/ServicePage/FAQ";
import {useEffect, useState} from "react";

const colorWhite = theme.colors.white;
const colorBlack = theme.colors.black;

const Service = ({ title, text, content, bestSuitedFor, workflowSetUp }: IService) => {
  const [menuColor, setMenuColor] = useState('none');
  const handleScroll = () => {
    window.scrollY >= 50
      ? setMenuColor(colorBlack)
      : setMenuColor('none')
  }

  useEffect(() => {
    window.addEventListener('scroll', handleScroll)

    return () => window.removeEventListener('scroll', handleScroll);
  })

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <MainMenu
          backgroundColor={menuColor}
          titlesColor={colorWhite}
          titles={titles}
        >
          <HeaderService title={title} text={text}/>
          <Information content={content}/>
          <BestSuitedFor title={bestSuitedFor.title} info={bestSuitedFor.info}/>
          <WorkflowSetUp title={workflowSetUp.title} content={workflowSetUp.content}/>
          <FAQ/>
          <LetsTalk
            flexDirection={'column-reverse'}
            title={'ready to start?'}
            text={'Get everything you need for the project initiation.'}
          />
        </MainMenu>
        <FooterComponent
            policies={footer.policies}
            offices={footer.offices}
            followUs={footer.followUs}
            pages={footer.pages}
            copyright={footer.copyright}
        />
      </>
    </>
  )
}

export default Service;

Service.getInitialProps = async({ query : { service }}: IServiceCTX) => {
  const text = servicesData[service]?.text;
  const content: IServicesDataInfoContent[] = servicesData[service]?.content;
  const bestSuitedFor: IServicesDataInfoBestSuitedFor = servicesData[service]?.bestSuitedFor;
  const workflowSetUp: IServicesDataInfoBestSuitedFor = servicesData[service]?.workflowSetUp;

  const res = {
    title: service,
    text,
    content,
    bestSuitedFor,
    workflowSetUp,
  }

  return res;
}
