import Head from "next/head";
import React from "../../public/SVG/technologies/react.svg";
import MainMenu from "../../components/mainMenu/mainMenu";
import FooterComponent from "../../components/Footer";
import { theme } from "../../styles/theme";
import { footer, titles, servicesPage } from "../../constants";
import ServicesComponent from "../../components/Services";
import InformationComponent from "../../components/Services/Information";
import TechStack from "../../components/Services/TechStack";
import LetsTalk from "../../components/Services/LetsTalk";

function Services() {
  const colorWhite = theme.colors.white;
  const colorBlack = theme.colors.black;

  return (
      <>
        <Head>
          <title>Incora | Services</title>
          <meta name="services" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <MainMenu
          backgroundColor={colorWhite}
          titles={titles}
          titlesColor={colorBlack}
        >
          <ServicesComponent/>
          <InformationComponent bgColor={'#181819'} info={servicesPage.info}/>
          <TechStack stacks={servicesPage.techStacks} stackTitle={servicesPage.techStackTitle}/>
          <LetsTalk
            flexDirection={'column'}
            title={'Let’s talk!'}
            text={
              <>
                <p>Got no clue where to start?</p>
                <p> Why don’t we discuss your idea?</p>
              </>
            }
          />
        </MainMenu>
        <FooterComponent {...footer}/>
      </>
  )
}

export default Services;
