import Head from 'next/head'
import MainMenu from "../components/mainMenu/mainMenu";

const titles = ['Services', 'Expertise', 'Case Studies', 'Company', 'Insights', 'Contact Us'];
const bgCover = '#18181A;';

function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <MainMenu titles={titles} backgroundColor={bgCover}>
      </MainMenu>
    </div>
  )
}

export default Home;
