import type { NextPage } from 'next'
import Head from 'next/head'
import MainMenu from "../components/mainMenu/mainMenu";
import Header from "../components/homePage/header/header";
import CooperateComponent from "../components/homePage/cooperate/cooperate.component";
import ServicesComponent from "../components/homePage/services/services.component";

const titles = ['Services', 'Expertise', 'Case Studies', 'Company', 'Insights', 'Contact Us'];
const bgCover = '#18181A;';
const sliders = [
  { title: 'How to Cooperate?',
    mainTitle: 'Outline your idea',
    text: 'Define the project you are working on. Let us analyze all requirements and documentation in order to conduct the relevant estimate.',
    redirectTo: 'outline-your-idea'
  },
  { title: 'How to Cooperate?',
    mainTitle: 'Get into specifics',
    text: 'We will discuss expectations, best practices, and the development process. Then you’ll choose the best fitting candidates for your project.',
    redirectTo: 'get-into-specifics'
  },
  { title: 'How to Cooperate?',
    mainTitle: 'Go Through the Development Stage',
    text: 'Get quality service and expert recommendations throughout all the cooperation. Develop your idea into a solid product.',
    redirectTo: 'go-through-the-development-stage'
  },
  { title: 'How to Cooperate?',
    mainTitle: 'Launch a Project',
    text: 'When your product is in production, we’ll provide you with maintenance to test the software, and make adjustments.',
    redirectTo: 'launch-a-project'
  }
];

const services = {
  title: 'Services',
  text: 'Working with dozens of custom projects we’ve come up to the set of services to cover up the whole workflow process your project might require. We are here to take all the challenges on ourselves and leave you nothing but relief.',
  labels: ['Software development ', 'UI/UX Design', 'R&D discovery phase', 'Team Extension', 'Dedicated Team', 'Web/Mobile App Development', 'DevOps', 'Software QA & Testing']
};

const plusesColor = '#FEC602';

function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <MainMenu titles={titles} backgroundColor={bgCover}>
        <Header />
        <CooperateComponent sliders={sliders} plusesColor={plusesColor}/>
        <ServicesComponent title={services.title} text={services.text} labels={services.labels}/>
      </MainMenu>
    </div>
  )
}

export default Home
